# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Cristiano Patrício
title: Ph.D. Student in Computer Science and Engineering | Research Assistant at INESC TEC
email: cristiano.patricio@ubi.pt | cristiano.p.patricio@inesctec.pt
website: https://cristianopatricio.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  CristianoPatricio
linkedin_username: cristiano-patrício-a7284a119
orcid_username: 0000-0003-2215-3334

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
    Cristiano Patrício received a B.Sc. in Computer Science and Engineering (17/20) in 2019 from the Polytechnic of Guarda and his M.Sc. in Computer Science and Engineering (18/20) in 2021 from the University of Beira Interior. He received 1 Merit Scholarship in the 2018/2019 academic year. Cristiano is pursuing his Ph.D. in Computer Science and Engineering from the University of Beira Interior under a Ph.D. research grant from the Portuguese national funding agency for science (FCT). Cristiano is currently a Research Assistant at INESC TEC and was a visiting assistant at the Polytechnic of Guarda in the academic year of 2021/2022. Previously, Cristiano participated in developing solutions for the Altice Portugal Foundation (MagicContact Web) projects and for the "Perception for a Service Robot" project of NOVA-LINCS. His work focuses on developing inherently interpretable deep learning models for pathology diagnosis in medical imaging. His research interests include the topics of Explainable AI, Deep Learning and Medical Image Analysis. He authored 5 research papers in international conferences and journals.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# Publications Section
# publications_title: Publications #(Use this to override about more section title)
publications: |
    <p style="font-size:20px;"><b>Conferences</b></p>
    <ul style="list-style-type: none;" >
        <li>
            I. Rio-Torto, <b>C. Patrício</b>, H. Montenegro, T. Gonçalves. <a href="http://ceur-ws.org/Vol-3180/paper-116.pdf" style="color: #cf2e2e;" target="blank"><em>Detecting Concepts and Generating Captions from Medical Images: Contributions of the VCMI Team to ImageCLEFmed Caption 2022</em></a>. Conference and Labs of the Evaluation Forum (CLEF), 2022.
        </li>
        <br>
        <li>
            <b>C. Patrício</b>, and J. Neves. <a href="https://arxiv.org/pdf/2110.04535.pdf" style="color: #cf2e2e;" target="blank"><em>ZSpeedL - Evaluating the Performance of Zero-Shot Learning Methods using Low-Power Devices</em></a>. In Proceedings of the 17th IEEE International Conference on Advanced Video and Signal Based Surveillance (AVSS), 2021.
        </li>
        <br>
        <li>
            <b>C. Patrício</b>, and J. Neves. <a href="#" style="color: #cf2e2e;" target="blank"><em>Evaluating the Performance of Zero-Shot Learning Methods using Low-Power Devices</em></a>. In 27th Portuguese Conference on Pattern Recognition (RECPAD 2021), November 5, Évora, Portugal, 2021. 
        </li>
        <br>
        <li>
            <b>C. Patrício</b>, T. Lucas , C. Goncalves, N. Pinto, D. Freitas, L. Figueiredo. <a href="https://link.springer.com/chapter/10.1007%2F978-3-030-51828-8_107" style="color: #cf2e2e;" target="blank"><em>MagicContact Web: A Multiplatform Application for Augmentative and Alternative Communication</em></a>. In: Ahram T., Falcão C. (eds) Advances in Usability, User Experience, Wearable and Assistive Technology. AHFE 2020. Advances in Intelligent Systems and Computing, vol 1217. Springer, Cham, doi: <a href="https://doi.org/10.1007/978-3-030-51828-8_107" style="color: #333; text-decoration: underline;">10.1007/978-3-030-51828-8_107</a>.
        </li>
    </ul>
    <br>
    <p style="font-size:20px;"><b>Journals</b></p>
    <ul style="list-style-type: none;" >
        <li>
            <b>C. Patrício</b>, and J. Neves. <a href="https://doi.org/10.1016/j.eswa.2022.118635" style="color: #cf2e2e;" target="blank"><em>Zero-Shot Face Recognition: Improving the Discriminability of Visual Face Features Using a Semantic-Guided Attention Model</em></a>. Expert Systems With Applications, 2022, 118635, doi: <a href="https://doi.org/10.1016/j.eswa.2022.118635" style="color: #333; text-decoration: underline;">10.1016/j.eswa.2022.11863</a>.
        </li>
    </ul>
    <br>
    <p style="font-size:20px;"><b>Book Chapters</b></p>
    <ul style="list-style-type: none;" >
        <li>
        <b>C. Patrício</b>, R. Pinto, G. Marques. <a href="https://link.springer.com/chapter/10.1007/978-3-030-47411-9_3#citeas" style="color: #cf2e2e;" target="blank"><em>A Study on Software Testing
    Standard Using ISO/IEC/IEEE 29119-2: 2013</em></a>. In: Al-Emran M., Shaalan K.,
    Hassanien A. (Eds.) Recent Advances in Intelligent Systems and Smart
    Applications. Studies in Systems, Decision and Control, vol 295, Springer,
    pp. 43-62, doi: <a href="https://doi.org/10.1007/978-3-030-47411-9_3" style="color: #333; text-decoration: underline;">10.1007/978-3-030-47411-9_3</a>, 2020.
        </li>
    </ul>
    <br>
    <p style="font-size:20px;"><b>Thesis</b></p>
    <ul style="list-style-type: none;" >
        <li>
            <b>C. Patrício</b>. <a href="" style="color: #cf2e2e;" target="blank"><em>A zero-shot learning method for recognizing objects using low-power devices</em></a>. MSc Thesis, Universidade da Beira Interior, Covilhã, Portugal, 2021. 
        </li>
    </ul>
    <br>
    <p style="font-size:20px;"><b>Electronic Articles</b></p>
    <ul style="list-style-type: none;" >
        <li>
            <b>C. Patrício</b>. (2019) "Apache Hadoop - Instalação e configuração de um cluster no Ubuntu 18.04", Pplware. Available: <a style="color: #333; text-decoration: underline;" href="https://pplware.sapo.pt/tutoriais/apache-hadoop-instalacao-ubuntu/">https://pplware.sapo.pt/tutoriais/apache-hadoop-instalacao-ubuntu/</a>.
        </li>
        <br>
        <li>
            <b>C. Patrício</b>. (2019) "Node.js: Criar em 5 minutos uma app de
            geolocalização do seu endereço IP",
            Pplware. Available: <a href="https://pplware.sapo.pt/tutoriais/node-js-endereco-ip/" style="color: #333; text-decoration: underline;">https://pplware.sapo.pt/tutoriais/node-js-endereco-ip/</a>.
        </li>
        <br>
        <li>
            <b>C. Patrício</b>. (2019) "Criação de uma máquina virtual com VMware
            Workstation Player", Pplware.
            Available: <a href="https://pplware.sapo.pt/software/criacao-de-uma-maquina-virtual-com-vmware-workstation/" style="color: #333; text-decoration: underline;">https://pplware.sapo.pt/software/criacao-de-uma-maquina-virtual-com-vmware-workstation/</a>.
        </li>
    </ul>

# Peer Review Section
# peerreview_title: Peer Review #(Use this to override about more section title)
peerreview: |
    <p style="font-size:20px;"><b>International Conferences</b></p>
    <ul>
        <li>
            IEEE International Conference on Advanced Video and Signal-Based Surveillance (AVSS), 2022
        </li>
        <li>
            Workshop on Interpretability of Machine Intelligence in Medical Image Computing (iMIMIC) at MICCAI, 2022
        </li>
        <li>
            IEEE World Congress on Computational Intelligence (WCCI), 2022
        </li>
        <li>
            EAI GOODTECHS 2021 - EAI International Conference on Smart Objects and Technologies for Social Good
        </li>
    </ul>
    <br>
    <p style="font-size:20px;"><b>International Journals</b></p>
    <ul>
        <li>
            Pattern Recognition
        </li>
        <li>
            NeuroImage
        </li>
    </ul>


# Programming Skills Section
# programming_title: Programming Skills #(Use this to override about more section title)
programming: |
  <table>
    <thead style="font-size:18px;">
    <tr>
        <th style="text-align:center">Language</th>
        <th style="text-align:center">Level of Expertise</th>
    </tr>
    </thead>
    <tbody style="font-size:14px;">
    <tr>
        <td style="text-align:center">Python</td>
        <td style="text-align:center">
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
        </td>
    </tr>
    <tr>
        <td style="text-align:center">Java</td>
        <td style="text-align:center">
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="far fa-circle"/>
        </td>
    </tr>
    <tr>
        <td style="text-align:center">C</td>
        <td style="text-align:center">
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="far fa-circle"/>
        </td>
    </tr>
    <tr>
        <td style="text-align:center">C#</td>
        <td style="text-align:center">
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="far fa-circle"/>
            <i class="far fa-circle"/>
        </td>
    </tr>
    <tr>
        <td style="text-align:center">JavaScript</td>
        <td style="text-align:center">
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="far fa-circle"/>
        </td>
    </tr>
    <tr>
        <td style="text-align:center">PHP</td>
        <td style="text-align:center">
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="far fa-circle"/>
            <i class="far fa-circle"/>
        </td>
    </tr>
    <tr>
        <td style="text-align:center">ASP.NET</td>
        <td style="text-align:center">
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="far fa-circle"/>
            <i class="far fa-circle"/>
        </td>
    </tr>
    <tr>
        <td style="text-align:center">SQL</td>
        <td style="text-align:center">
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="far fa-circle"/>
            <i class="far fa-circle"/>
        </td>
    </tr>
    <tr>
        <td style="text-align:center">PL-SQL</td>
        <td style="text-align:center">
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="far fa-circle"/>
            <i class="far fa-circle"/>
        </td>
    </tr>
    <tr>
        <td style="text-align:center">MySQL</td>
        <td style="text-align:center">
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="far fa-circle"/>
            <i class="far fa-circle"/>
        </td>
    </tr>
    <tr>
        <td style="text-align:center">Postgres</td>
        <td style="text-align:center">
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="fas fa-circle"/>
            <i class="far fa-circle"/>
            <i class="far fa-circle"/>
        </td>
     </tr>
     </tbody>
  </table>

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  Outside the office, I like to read a nice book, play chess or play guitar/accordion. I'm a curious guy who spends time learning new things to keep soft skills refined. 
  <br><br>
  <p><em>Selected Quotes:</em></p>
  <ul style="list-style-type: none;">
    <li><em>"Hard work always pays off, whatever you do."</em> - Dustin Lynch</li>
    <li><em>"If you want to master something, teach it. The more you teach, the better you learn. Teaching is a powerful tool to learning."</em> - Richard P. Feynman</li>
  </ul>

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
