site_name: Deucalion User Guide - UBI
site_url: https://cristianopatricio.github.io/deucalion/
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Running Jobs: running-jobs.md
  - Containers: containers.md
  - Interactive Sessions: interactive-sessions.md
  - About: about.md
theme: readthedocs